// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import FavouritesController from "./favourites_controller"
application.register("favourites", FavouritesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import PlatformController from "./platform_controller"
application.register("platform", PlatformController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShareController from "./share_controller"
application.register("share", ShareController)
